### ISSUE TITLE
Uploading content to GoogleDrive using R

### ISSUE THREAD

**Issue by oskasf** [daaronr/dr-rstuff#7]
Relatively simple to upload a file to gdrive using the *googledrive* package from the Tidyverse. 

`library(googledrive)`

`rmarkdown::render("test/test.Rmd")`

`drive_upload(media="test/test.html", path=as_dribble("GDrive test folder"), overwrite=TRUE)`

Note that using `as_dribble()` allows us to specify the path to upload to in GDrive. We want to specify `overwrite=TRUE` in order to ensure that we don't end up with duplicate copies of files. This will search for our file and overwrite if it exists. 

^ Note this only uploads the raw html (not useful)

**Comment by oskasf** [comment]
@daaronr Obviously the above example is relatively simple, it would be easy to expand this to uploading multiple files using a for loop and the `list.files` function!

**Comment by daaronr** [comment]
Thanks! I'll think about a good 'first use case' of this, and then we can
try it out on a real example and share it!
